logging:
  level:
    com.example.demo: DEBUG
    org.apache.kafka: WARN

spring:
  application:
    name: simple-kafka-demo-app
    instance-id: ${spring.application.name}-${random.uuid} # Custom property for instance id


  kafka:
    bootstrap-servers: localhost:29092 # Kafka will start automatically on port 29092 by compose.yml
    client-id: ${spring.application.instance-id}

    producer:
      # Custom property for producer topics names
      topics:
        person-email-updates: com.example.person.email.events

    consumer:
      # Custom property for consumer topics names
      topics:
        # Payload example: {"id: 1001, "email": "john.doe@gmail.com"}
        person-email-updates: com.example.person.email.events

      # Unique string identifying the consumer group. No default, must be set if group management is used.
      group-id: ${spring.application.name}
